### ISSUE TITLE
tags not find (cooverview line 118.)

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/cooverview#1]
For every image on registry.opensuse.org I get:

404 Not Found (http://localhost/v2/cloudplatformstackrootfsimagessle15/tags/list) at /srv/www/cgi-bin/cooverview line 118.

**Comment by M0ses** [comment]
Cannot reproduce

**Comment by thkukuk** [comment]
On Wed, Apr 01, Frank Schreiner wrote:

> Cannot reproduce

https://registry.opensuse.org, click on any container image and you
will get that error. Everybody in my team can reproduce that.

**Comment by M0ses** [comment]
As discussed with @thkukuk personally, the problem seems to be gone now.

Just for the record: If you run into this problem, make sure that you clear your browser's cache
